In [1]:
import numpy as np
P = np.matrix([[9/10,1/10],[1/2,1/2]])
P               # display P

matrix([[0.9, 0.1],
        [0.5, 0.5]])

In [5]:
P0= np.matrix([1,0])
P0

matrix([[1, 0]])

In [6]:
P2= P0*P**2

In [7]:
P2

matrix([[0.86, 0.14]])

In [9]:
N=5
day0= np.matrix([0,1])
day5= day0*P**5
day5

matrix([[0.8248, 0.1752]])

In [10]:
evalues, evecs= np.linalg.eig(P.T)
evalues, evecs

(array([1. , 0.4]),
 matrix([[ 0.98058068, -0.70710678],
         [ 0.19611614,  0.70710678]]))

In [11]:
firsevec= evecs[:, 0]

In [13]:
np.array(firsevec)/np.sum(firsevec)

array([[0.83333333],
       [0.16666667]])